### ISSUE TITLE
Display colors to Folders sidebar reflecting Git status

### ISSUE THREAD

**Issue by xwartz** [kemayo/sublime-text-git#481] opened 2016-07-09 10:02 UTC
Like Atom

![image](https://cloud.githubusercontent.com/assets/4149827/16707425/3bb833ba-45ff-11e6-94a5-4b4265f40279.png)

**Comment by josegonzalez** [comment] 2016-08-30 10:30
Duplicate of https://github.com/kemayo/sublime-text-git/issues/204, so this should be closed.

**Closed** 2016-08-30 10:47 UTC

**Comment by kemayo** [comment] 2016-08-30 15:29
Indeed. As said in #204, the APIs for this aren't there.
